### ISSUE TITLE
Domain registration

### ISSUE THREAD

**Issue by ghermans** [ghermans/idev_office#1]
# Description

We need a  page to register domain names, this should be done by the OpenProvider API.
# Todo
- [ ] Create view page for domain creation (domain,tld, person/company info)
- [ ] Register the domain true the OpenProvider API
- [ ] Register the domain in Plesk for DNS
