### ISSUE TITLE
SMS center

### ISSUE THREAD

**Issue by ghermans** [ghermans/idev_office#3]
# Description

Send SMS messages to customers with the smstools api.
# Todo
- [ ] Create view page (mobile_number,message)
- [ ] Log SMS details in the database
- [ ] Send SMS with the smstools api.
